/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeSpeed */

#ifndef _Included_NativeSpeed
#define _Included_NativeSpeed
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeSpeed
 * Method:    doNativeFunc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeSpeed_doNativeFunc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
