#!/bin/sh
cp bsh-2.0b2.jar beanking.jar
javac -classpath beanking.jar:../../king/king.jar BeanKing.java \
&& jar uvf beanking.jar BeanKing.class *.bsh META-INF/services/king.Plugin king/king_prefs \
&& cp -v beanking.jar ../../king/plugins/

