#!/bin/sh
javadoc -d javadocs \
-quiet \
-source 1.5 \
-windowtitle "IWD's JavaDocs" \
-breakiterator \
-noqualifier all \
-linksource \
-protected \
-classpath lib:lib/iText/itext-1.02b.jar \
-sourcepath chiropraxis/src:driftwood/src:extratools/src:fftoys/src:king/src:molikin/src:silk/src:dangle/src \
-subpackages chiropraxis:driftwood:fftoys:Jama:jnt:king:molikin:silk:dangle
