#!/bin/bash
set verbose
##############################################################################
# MUST RUN ant dist BEFORE THIS SCRIPT!
##############################################################################

# First, update Rlab's copy:
# ./deploy-rlab

# Copy src, jars to download site for distribution:
scp dist/king.?.??.??????*.zip kinemage.biochem.duke.edu:/websites/kinemage/downloads/software/king/.

# Provide ZIP for auto-update:
scp dist/king.?.??.??????.zip kinemage.biochem.duke.edu:/websites/kinemage/downloads/software/king/current2

# Update marker for auto-update:
scp resource/king/version.props kinemage.biochem.duke.edu:/websites/kinemage/downloads/software/king/king2.version.props

# Update docs on website:
scp -r dist/king-?.??/doc/. kinemage.biochem.duke.edu:/websites/kinemage/downloads/software/king/docs

# Update manual on website:
scp resource/king/html/king-manual.html kinemage.biochem.duke.edu:/websites/kinemage/kinemage/king-manual.html

# Update manual pdf on website:
scp doc/king-manual.pdf kinemage.biochem.duke.edu:/websites/kinemage/downloads/PDFs/king-manual.pdf 

#
# MolProbity will be updated separately, with a new king.jar in Subversion.
#

echo "*** REMEMBER TO REBUILD THE WINDOW AND LINUX BUNDLES ***"
echo "*** REMEMBER TO MAKE A MAC DMG AND UPDATE THE VERSION NUMBER IN INFO.PLIST ***"
