#!/bin/sh
javadoc -d javadocs \
-quiet \
-source 1.4 \
-windowtitle "IWD's JavaDocs" \
-breakiterator \
-noqualifier all \
-linksource \
-protected \
-link /Users/ian/Documents/javadoc-1.4.2/api/ \
-classpath lib:lib/iText/itext-1.02b.jar \
-sourcepath chiropraxis/src:driftwood/src:fftoys/src:king/src:silk/src \
-subpackages chiropraxis:driftwood:fftoys:jnt:king:silk
